#file:
#  upload-dir: D:\\JavaProjects\\Sulu\\images\\

spring:
  datasource:
    url: jdbc:postgresql://base-archetype-test-postgres.postgres.database.azure.com:5432/test
    username: postgres@base-archetype-test-postgres
    password: 12345Abc!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 15MB
      max-request-size: 15MB
#  flyway:
#    baseline-on-migrate: true